[package]
name = "jsompiler"
version = "0.1.0"
edition = "2024"
description = "a Json syntax programming language for Windows"
license = "Apache-2.0"
repository = "https://github.com/HAL-G1THub/jsompiler.git"
[[bin]]
name = "jsompiler"
path = "src/main.rs"
[profile.release]
lto = true
panic = "abort"
