max_width = 100
hard_tabs = false
tab_spaces = 2
newline_style = "Unix"
use_small_heuristics = "Max"
reorder_modules = true
remove_nested_parens = true
short_array_element_width_threshold = 10
match_arm_leading_pipes = "Never"
fn_params_layout = "Compressed"
match_block_trailing_comma = false
edition = "2024"
style_edition = "2024"
merge_derives = true
use_try_shorthand = true
use_field_init_shorthand = true
force_explicit_abi = true
disable_all_formatting = false
